### ISSUE TITLE
Atom.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by Stephen304** [suda/yuno-commit#5]
Just putting this here.

atom.workspaceView is no longer available.
In most cases you will not need the view. See the Workspace docs for
alternatives: https://atom.io/docs/api/latest/Workspace.
If you do need the view, please use `atom.views.getView(atom.workspace)`,
which returns an HTMLElement.
```
Atom.Object.defineProperty.get (/usr/share/atom/resources/app.asar/src/atom.js:57:13)
YunoCommitView.initialize (/home/stephen/.atom/packages/yuno-commit/lib/yuno-commit-view.coffee:21:42)
YunoCommitView.View (/usr/share/atom/resources/app.asar/node_modules/space-pen/lib/space-pen.js:145:25)
new YunoCommitView (/home/stephen/.atom/packages/yuno-commit/lib/yuno-commit-view.coffee:18:51)
Object.activate (/home/stephen/.atom/packages/yuno-commit/lib/yuno-commit.coffee:7:26)
Package.activateNow (/usr/share/atom/resources/app.asar/src/package.js:238:19)
```

**Comment by dtinth** [comment]
I published a fork of yuno-commit, called [yuno-commit-plus](https://atom.io/packages/yuno-commit-plus), which supports Atom 1.0.

**Comment by suda** [comment]
@dtinthit I welcome all PR's :) It would be great if you could merge your changes into this repo and then we could have one package that does it all :)

**Comment by dtinth** [comment]
Hello.

I thought the project is now inactive, that’s why I published a forked version instead. As of writing, there is one more bug for me to fix, when the project does not have a Git repository, and hopefully, we can merge them afterwards.

Here's a comparison of the fork: https://github.com/suda/yuno-commit/compare/master...dtinth:master

I moved a lot of code out of the view, and used reactive programming for a more robust event handling. These changes are quite radical, which is another reason I went the fork path.

If you think that these changes are fine, you can add me as a collaborator to your GitHub repository, so that [I can release new versions with minimal friction](https://atom.io/docs/latest/behind-atom-maintaining-your-packages#adding-a-collaborator). :smile:

**Comment by suda** [comment]
That is amazing man! I've added you as a collaborator but create a PR first and I'll check the full changes then :)
